config/routes.rb
Rails.application.routes.draw do

  resources :users,:sessions
  resources :games, except: [:destroy] do
    resources :add_ons
  end

  root :to => 'games#index'  #RAILS 3

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
end

app/models/add_on.rb
class AddOn < ApplicationRecord
  belongs_to :game
  monetize :cost_cents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :add_ons
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/add_ons_controller.rb
class AddOnsController < ApplicationController
  before_action :find_game
  before_action :set_add_on, only: [:show, :edit, :update, :destroy]

  # GET /add_ons
  # GET /add_ons.json
  def index
    @add_ons = @game.add_ons.all
  end

  # GET /add_ons/1
  # GET /add_ons/1.json
  def show
  end

  # GET /add_ons/new
  def new
    @add_on = @game.add_ons.new
  end

  # GET /add_ons/1/edit
  def edit
  end

  # POST /add_ons
  # POST /add_ons.json
  def create
    @add_on = @game.add_ons.new(add_on_params)

    respond_to do |format|
      if @add_on.save
        format.html { redirect_to @game, notice: 'Add on was successfully created.' }
        format.json { render :show, status: :created, location: @add_on }
      else
        format.html { render :new }
        format.json { render json: @add_on.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_ons/1
  # PATCH/PUT /add_ons/1.json
  def update
    respond_to do |format|
      if @add_on.update(add_on_params)
        format.html { redirect_to [@game, @add_on], notice: 'Add on was successfully updated.' }
        format.json { render :show, status: :ok, location: @add_on }
      else
        format.html { render :edit }
        format.json { render json: @add_on.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_ons/1
  # DELETE /add_ons/1.json
  def destroy
    @add_on.destroy
    respond_to do |format|
      format.html { redirect_to add_ons_url, notice: 'Add on was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_on
      @add_on = @game.add_ons.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def add_on_params
      params.require(:add_on).permit(:game_id, :title, :description, :cost)
    end

    def find_game
      @game = Game.find(params[:game_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:edit, :show, :update]

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game
    else
    end
  end


  def edit
  end


  def index
    @games = Game.order(name: :asc)
  end


  def new
    @game = Game.new
  end


  def show
    @add_ons = @game.add_ons
  end


  def update
    @game.update(game_params)
    redirect_to @game
  end

protected

  def find_game
    @game = Game.find(params[:id])
  end


  def game_params
    params[:game].permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.password == (params[:session][:password])
      log_in user
      redirect_to user
    end
  end


  def destroy
  end


  def new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :show, :update]

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
    end
  end


  def edit
  end


  def index
    @user = User.order(name: :asc)
  end


  def login
    @user = User.find(params[:username,:password])
  end

  def new
    @user = User.new
  end


  def show

  end


  def update
    @user.update(user_params)
    redirect_to @user
  end

protected

  def find_user
    @user = User.find(params[:id])
  end


  def user_params
    params[:user].permit(:id,:username,:password,:email)
  end
end

app/helpers/add_ons_helper.rb
module AddOnsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/add_ons/_form.html.erb
<%= simple_form_for([@game, add_on]) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :cost %>
  <%= f.submit "Save", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/add_ons/edit.html.erb
<h1>Editing Add On</h1>

<%= render 'form', add_on: @add_on %>

app/views/add_ons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Add Ons</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Title</th>
      <th>Description</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @add_ons.each do |add_on| %>
      <tr>
        <td><%= add_on.game_id %></td>
        <td><%= add_on.title %></td>
        <td><%= add_on.description %></td>
        <td><%= add_on.cost %></td>
        <td><%= link_to 'Show', add_on %></td>
        <td><%= link_to 'Edit', edit_add_on_path(add_on) %></td>
        <td><%= link_to 'Destroy', add_on, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Add On', [:new, @game, :A] %>

app/views/add_ons/new.html.erb
<h1>New Add On</h1>

<%= render 'form', add_on: @add_on %>

app/views/add_ons/show.html.erb
<div class="page-header">
  <div class="pull-xs-right">
    <%= link_to("Edit", [:edit, @game, @add_on], class: "btn btn-secondary") %>
  </div>
  <h1><%= @game.name %></h1>
  <h2><%= @add_on.title %></h2>
  $<%= @add_on.cost %>
  <br>
  <%= @add_on.description %>
</div>

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Save" %>
<% end %>

app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= render "form" %>

app/views/games/index.html.erb
<div class="page-header">
  <div class="pull-xs-right">
    <%= link_to "New Game", new_game_path, class: "btn btn-secondary" %>
  </div>
  <h1>Games</h1>
</div>

<div class="row">
  <% @games.each do |game| %>
    <div class="col-xs-6 col-md-3">
      <div class="card">
        <div class="card-block">
          <div class="caption">
            <%= link_to(game.name, game) %><br />
            <span class="text-muted"><%= pluralize(game.add_ons.count, "Add On") %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

app/views/games/show.html.erb
<div class="page-header">
  <%= link_to("Edit", [:edit, @game], class: "btn btn-secondary pull-xs-right") %>
  <h1><%= @game.name %></h1>
</div>

<section>
  <%= link_to("New AddOn", [:new, @game, :add_on], class: "btn btn-secondary pull-xs-right") %>
  <h2>Add Ons</h2>
  <div class="row">
    <% @add_ons.each do |add_on| %>
      <div class="col-xs-6 col-md-3">
        <div class="card">
          <div class="card-block">
            <div class="caption">
              <%= link_to(add_on.title, [@game, add_on]) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magicus</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>

<nav class="navbar navbar-light bg-faded navbar-fixed-top">
  <div class="container-fluid">
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
      &#9776;
    </button>
    <a class="navbar-brand" href="/">Magicus</a>
    <div class="collapse navbar-collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <ul class="nav navbar-nav">
        <li class="nav-item <%= "active" if params[:controller] == "games" %>"><%= link_to("Games", :games, class: "nav-link") %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :username %>
  <%= f.text_field :password %>
  <%= f.text_field :email %>
  <%= f.submit "Save", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/users/edit.html.erb
<h1>Account Settings</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="page-header">
  <div class="pull-xs-right">
    <%= link_to "New User", new_user_path, class: "btn btn-secondary" %>
  </div>
  <h1>Users</h1>
</div>

<div class="row">
  <% @user.each do |user| %>
    <div class="col-xs-6 col-md-3">
      <div class="card">
        <div class="card-block">
          <div class="caption">
            <%= link_to(user.username, user) %><br />
            <span class="text-muted"><%= user.email %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/login.html.erb
<h1>login</h1>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <%= link_to("Edit", [:edit, @user], class: "btn btn-secondary pull-xs-right") %>
  <h1><%= @user.username %></h1>
</div>

<section>
  <h2>Info</h2>
  <div class="row">
    <%= @user.password %>
    <%= @user.email %>
  </div>
</section>